name: Informational
description: 'Quick docs, when they're needed.'
title: "[Info] <Short description>"
labels: [documentation]
body:
- type: textarea
  id: version
  attributes:
    label: Describe the bug
    description: |
      A clear and concise description of what the bug is.
    placeholder: 'Example: Login results in a crash'
  validations:
    required: true

- type: textarea
  attributes:
    label: Add some background
    description: |
      What's this documentation for? If it's a solution doc, what's causing the issue? Why is it important to document?
  validations:
    required: true

- type: textarea
  attributes:
    label: Time to document.
    description: |
      Write the documentation here. Solutions, simple tricks, screenshots and other goodies belong in this section.
  validations:
    required: true

- type: textarea
  attributes:
    label: Disclaimers
    description: If you're posting a solution this risky, post a disclaimer saying it is!
  validations:
    required: false
