name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      
      - name: static to dylib
        run: |
          cd jniLibs
          a2dylib { clang -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk -target arm64-apple-ios9.0 -fpic -shared -Wl,-all_load lib$1.a -o lib$1.dylib }
          a2dylib glass
          a2dylib javafx_font
          a2dylib javafx_iio
          a2dylib javafx_ios_webnode
          a2dylib jfxmedia
          a2dylib prism_common
          a2dylib prism_es2
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: dylib
          path: jniLibs

      - name: Native build
        run: |
          cd Natives
          mkdir build
          cd build
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
          cmake --build . --config Release --target pojavexec PojavLauncher
          cd ../..
          cp Natives/build/Release-iphoneos/libpojavexec.dylib PojavLauncher.app/Frameworks/

      - name: Java Build
        run: |
          cd JavaApp
          chmod +x gradlew
          ./gradlew clean build
          cd ..
          mkdir PojavLauncher.app/libs
          cp JavaApp/build/libs/*.jar PojavLauncher.app/libs
          
      - name: Package IPA
        run: |
          mkdir Payload
          mv PojavLauncher.app Payload/
          zip -r PojavLauncher.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher
          path: PojavLauncher.ipa

