name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Native build
        run: bash build_natives_clang.sh

      - name: Java app Build
        run: bash build_javaapp.sh
          
      - name: Sign and Package deb
        run: bash build_package.sh
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher deb
          path: packages/pojavlauncher_iphoneos-arm.deb


