name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2

      - name: Setup Dependencies
        run: brew install ldid dpkg fakeroot
        
      - name: Setup Clang build
        run: bash scripts/actions_setup.sh

      - name: Native build
        run: bash scripts/build_natives_clang.sh

      - name: Java app Build
        run: bash scripts/build_javaapp.sh
          
      - name: Sign and Package deb
        run: bash scripts/build_package.sh
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher deb
          path: packages/pojavlauncher_iphoneos-arm.deb


