name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      
      - name: Native build
        run: |
          cd Natives
          mkdir build
          cd build
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
          cmake --build . --config Release --target pojavexec
          cd ../..
          cp Natives/build/Release-iphoneos/libpojavexec.dylib PojavLauncher.app/Frameworks/

      - name: Java Build
        run: |
          cd JavaApp
          chmod +x gradlew
          ./gradlew clean build
          cd ..
          mkdir PojavLauncher.app/libs
          cp JavaApp/build/libs/*.jar PojavLauncher.app/libs
          
      - name: Package IPA
        run: |
          mkdir Payload
          mv PojavLauncher.app Payload/
          zip -r PojavLauncher.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher
          path: PojavLauncher.ipa

