name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      
      - name: Native build
        run: |
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cd src/main/jni
          mkdir build
          cd build
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DSTATICLIB=ON -DPLATFORM=OS64
          cmake --build . --config Release --target GL
          cd ../..
          cp jni/build/Release/libpojavexec.a jniLibs/

      - name: RoboVM Build
        run: |
          chmod +x gradlew
          ./gradlew -Probovm.archs=arm64 clean createIPA
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher
          path: build/robovm/PojavLauncher.ipa

