name: iOS build

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'

      - uses: actions/checkout@v2
      
#      - name: static to dylib
#        run: |
#          cd jniLibs
#          clang -fpic -shared -Wl,-all_load libglass.a -o libglass.dylib
#          clang -fpic -shared -Wl,-all_load libjavafx_font.a -o libjavafx_font.dylib
#          clang -fpic -shared -Wl,-all_load libjavafx_iio.a -o libjavafx_iio.dylib
#          clang -fpic -shared -Wl,-all_load libjavafx_ios_webnode.a -o libjavafx_ios_webnode.dylib
#          clang -fpic -shared -Wl,-all_load libjfxmedia.a -o libjfxmedia.dylib
#          clang -fpic -shared -Wl,-all_load libprism_common.a -o libprism_common.dylib
#          clang -fpic -shared -Wl,-all_load libprism_es2.a -o libprism_es2.dylib

      - name: Native build
        run: |
          cd Natives
          mkdir build
          cd build
          wget https://github.com/leetal/ios-cmake/raw/master/ios.toolchain.cmake
          cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=ios.toolchain.cmake -DPLATFORM=OS64 -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED="NO" -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_ALLOWED=NO -DCMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY=""
          cmake --build . --config Release --target pojavexec PojavLauncher
          cd ../..
          mkdir -p Natives/build/Release-iphoneos/PojavLauncher.app/Frameworks
          cp Natives/build/Release-iphoneos/libpojavexec.dylib Natives/build/Release-iphoneos/PojavLauncher.app/Frameworks/

      - name: Java Build
        run: |
          cd JavaApp
          chmod +x gradlew
          ./gradlew clean build
          cd ..
          mkdir Natives/build/Release-iphoneos/PojavLauncher.app/libs
          brew install tree
          tree
          cp JavaApp/build/libs/PojavLauncher-1.0.jar Natives/build/Release-iphoneos/PojavLauncher.app/launcher.jar
          
      - name: Sign and Package IPA
        run: |
          mkdir Payload
          mv Natives/build/Release-iphoneos/PojavLauncher.app Payload/
          codesign -fs "PojavLauncher" --entitlements entitlements.xml Payload/PojavLauncher.app/PojavLauncher
          zip -r PojavLauncher.ipa Payload
          
      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: PojavLauncher
          path: PojavLauncher.ipa

